export default {
  SET_CURRENT_PANEL: 'SET_CURRENT_PANEL',
  SET_FARTHEST_PANEL: 'SET_FARTHEST_PANEL',
  SET_LAST_PANEL: 'SET_LAST_PANEL',
  SET_PREVIEW_3D: 'SET_PREVIEW_3D',
  SET_VISITED: 'SET_VISITED',
  SET_FILE: 'SET_FILE',
  SET_CURRENT_CHECKLIST_ITEM: 'SET_CURRENT_CHECKLIST_ITEM',
};
